version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "20"

  commands:
    - cd website
    - cd website && pwd
    - cd website && ls -la
    - cd website && npm ci
    - cd website && npm run build
    - cd website && mkdir -p $READTHEDOCS_OUTPUT/html/
    - cd website && cp -r build/* $READTHEDOCS_OUTPUT/html/