version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "20"

  commands:
    - cd website
    - pwd
    - ls -la
    - npm ci
    - npm run build
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - cp -r build/* $READTHEDOCS_OUTPUT/html/