version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    ports:
      - '3001:3000'
    environment:
      BACKEND_API_URL: http://backend:4000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  backend:
    build:
      context: ./backend
      args:
        APP_VERSION: ${APP_VERSION:-dev}
    ports:
      - '4000:4000'
      - '5555:5555'
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conducky
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 