version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - '3001:3000'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conducky
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 