services:
  - type: web
    name: conducky-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: conducky-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 4000
    healthCheckPath: /
    autoDeploy: true
    buildCommand: '' # Use Dockerfile
    startCommand: '' # Use Dockerfile
    
  - type: web
    name: conducky-frontend
    env: docker
    plan: free
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://conducky-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    buildCommand: '' # Use Dockerfile
    startCommand: '' # Use Dockerfile

databases:
  - name: conducky-db
    plan: free
    version: 15
    ipAllowList: [] # Only allow internal connections

# Notes:
# - The backend and frontend are deployed as separate web services using their respective Dockerfiles.
# - The backend gets its DATABASE_URL from the managed Postgres instance.
# - SESSION_SECRET is auto-generated for security.
# - NEXT_PUBLIC_API_URL in the frontend should match the backend's Render URL (update after first deploy if needed).
# - You may want to upgrade from the free plan for production use.
# - Add any additional env vars as needed for your app. 