name: Run Backend and Frontend Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:coverage
      - name: Run tests and generate CTRF report
        run: npm run test:ctrf
      - name: Check reports
        run: ls ctrf
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          pull-request-report: true
          report-path: 'backend/ctrf/ctrf-report.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: backend
          files: ./coverage/lcov.info
          name: backend-coverage

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:coverage
      - name: Run tests and generate CTRF report
        run: npm run test:ctrf
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          pull-request-report: true
          report-path: '/frontend/ctrf/ctrf-report.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          files: ./coverage/lcov.info
          name: frontend-coverage 
